### ISSUE TITLE
path handling on Windows platforms

### ISSUE THREAD

**Issue by rschmid47** [crystal/crystal#1]
I think the script "generate.coffee" on line 38 is not optimal/correct for Windows platforms. The code on this line 
  ```code_dir = path.substring 0, path.lastIndexOf('/')+1```
does explicit string handling assuming '/' to be the file separator which is not the case for Windows. E.g. the NodeJS module "fs" uses '\' on Windows platforms.

I suggest to use the platform-aware ```path.dirname()``` (from NodeJS module "path") to do computations with file paths.

**Comment by ctate** [comment]
Thanks for reporting this! Working on a fix.

**Comment by ctate** [comment]
Fixed in v0.8. Tested on Windows 10. Please let me know if you are still experiencing this issue. Thanks again for the bug report!
