### ISSUE TITLE
User account confirmation issues

### ISSUE THREAD

**Issue by JonTheNiceGuy** [crystal/crystal#5]
Received a "confirm your registration" email. Clicked the link (https://crystal.sh/user/verify/a93dacf9-e821-41bf-9840-f8c5b4ae4774), received "Page not found".

**Comment by ctate** [comment]
@JonTheNiceGuy We have decided to move all authentication to GitHub, so we no longer need an email confirmation to verify your account: https://crystal.sh/login

Thanks so much for reporting this issue!
