### ISSUE TITLE
Missing bin directory

### ISSUE THREAD

**Issue by jonathanjgacosta** [crystal/crystal#6]
Hi, I believe the bin directory is missing, I installed crystal using npm and the system doesn't recognize the command and when I tried to clone by git it's the same. 

Thank you in advance.

**Comment by ctate** [comment]
Hi @jonathanjgacosta - the CLI version of Crystal has been moved to https://github.com/crystal/crystal-cli. You can install it via npm: `npm install crystal-cli -g`

This repo (crystal/crystal) will remain as the JS version only - which is used as the core of both Crystal CLI and Crystal Studio.

Sorry for the confusion. Let me know if anything else comes up and don't hesitate to ask if you are looking for anything specifically.

Thank you!

**Comment by jonathanjgacosta** [comment]
Hi @ctate - thank you for your help. 

I was able to installed without any problem. I want to take a look to this fantastic code generator and I will write an article about it. It's a Spanish website but I think many developers will find it useful ;). 

Best regards!

**Comment by ctate** [comment]
@jonathanjgacosta Thank you so much for this excellent tutorial! My wife translated it for me. This is very exciting for our team. I'll be posting the link on our blog, and our tutorial section for others to check out. Thanks for your contribution!

**Comment by jonathanjgacosta** [comment]
Thanks to all the team! It's an excellent work and must be shared it ;)
